In [1]:
## Import for data generation
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
ID_21659081 = np.load("C:\\Users\\nico\\Desktop\\Stanford\\OneDrive - Stanford\\Courses\\CS229\\finalproject\\data\\United_States_Fires\\United_States_2019_Fires\\apr\\multi_day\\21659081.npy")

In [27]:
training_set = ID_21659081
x_train = []
y_train = []

n_future = 1
n_past = 5

for i in range(0 , len(training_set) - n_future - n_past + 1):
    x_train.append(training_set[i : i + n_past])
    y_train.append(training_set[i + n_past: i + n_past + n_future])

x_train, y_train = np.array(x_train), np.array(y_train)

x_train = np.reshape(x_train, (x_train.shape[1], x_train.shape[0], x_train.shape[2], x_train.shape[3]))
y_train = np.reshape(y_train, (y_train.shape[0], y_train.shape[2], y_train.shape[3]))

print(x_train.shape)
print(y_train.shape)



(7, 5, 235, 1538)
(7, 235, 1538)


In [4]:
print(x_train.shape)

(5, 7, 235, 1538)


In [5]:
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout
import tensorflow as tf

In [6]:
from pyspark import SparkContext
sc =SparkContext()

In [7]:
regressor = Sequential()

regressor.add(tf.keras.layers.Bidirectional(LSTM(units=n_past, return_sequences=True, input_shape = x_train[0].shape)))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = n_past, return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = n_past, return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = n_past, return_sequences = True))
regressor.add(Dropout(0.2))
regressor.add(Dense(units = n_future, activation = 'linear'))

regressor.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['acc'])
regressor.fit(x_train[0], y_train, epochs = 100, batch_size = 32)

Epoch 1/100
1/1 [==============================] - 5s 5s/step - loss: 0.0300 - acc: 0.9735
Epoch 2/100
1/1 [==============================] - 0s 208ms/step - loss: 0.0273 - acc: 0.9735
Epoch 3/100
1/1 [==============================] - 0s 199ms/step - loss: 0.0276 - acc: 0.9735
Epoch 4/100
1/1 [==============================] - 0s 207ms/step - loss: 0.0269 - acc: 0.9735
Epoch 5/100
1/1 [==============================] - 0s 196ms/step - loss: 0.0265 - acc: 0.9735
Epoch 6/100
1/1 [==============================] - 0s 197ms/step - loss: 0.0263 - acc: 0.9735
Epoch 7/100
1/1 [==============================] - 0s 204ms/step - loss: 0.0267 - acc: 0.9735
Epoch 8/100
1/1 [==============================] - 0s 192ms/step - loss: 0.0261 - acc: 0.9735
Epoch 9/100
1/1 [==============================] - 0s 189ms/step - loss: 0.0257 - acc: 0.9735
Epoch 10/100
1/1 [==============================] - 0s 199ms/step - loss: 0.0259 - acc: 0.9735
Epoch 11/100
1/1 [==============================] - 0s 194ms/s

1/1 [==============================] - 0s 205ms/step - loss: 0.0248 - acc: 0.9735
Epoch 88/100
1/1 [==============================] - 0s 200ms/step - loss: 0.0248 - acc: 0.9735
Epoch 89/100
1/1 [==============================] - 0s 193ms/step - loss: 0.0248 - acc: 0.9735
Epoch 90/100
1/1 [==============================] - 0s 195ms/step - loss: 0.0247 - acc: 0.9735
Epoch 91/100
1/1 [==============================] - 0s 198ms/step - loss: 0.0248 - acc: 0.9735
Epoch 92/100
1/1 [==============================] - 0s 199ms/step - loss: 0.0247 - acc: 0.9735
Epoch 93/100
1/1 [==============================] - 0s 198ms/step - loss: 0.0248 - acc: 0.9735
Epoch 94/100
1/1 [==============================] - 0s 190ms/step - loss: 0.0248 - acc: 0.9735
Epoch 95/100
1/1 [==============================] - 0s 193ms/step - loss: 0.0248 - acc: 0.9735
Epoch 96/100
1/1 [==============================] - 0s 196ms/step - loss: 0.0247 - acc: 0.9735
Epoch 97/100
1/1 [==============================] - 0s 194ms/st

In [26]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
training_set_scaled = sc.fit_transform(x_train[0][0])

predict_train = regressor.predict(training_set)


predicted_fires = sc.inverse_transform(x_train[0][0])

print(x_train[0][0])

print(np.sum(x_train[0][0]))

print(x_train.shape)

predicted_fires.shape

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
190681.0
(5, 7, 235, 1538)


(235, 1538)

In [25]:
print(np.sum(predicted_fires))

190681.0


In [ ]:
pip install sc-tool